config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#home'

  resources :issues do
    member do
      get 'preview'
    end
  end
  resources :articles, except: [:index]
  resources :categories, except: [:index, :show]
  resources :events

  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'clearance/sessions', only: [:create]

  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password,
      controller: 'clearance/passwords',
      only: [:create, :edit, :update]
  end

  get '/admin' => 'pages#admin', as: 'admin'
  get '/subscribe' => 'pages#subscribe', as: 'subscribe'

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  # get '/sign_up' => 'clearance/users#new', as: 'sign_up'
  get "sitemap.xml" => "sitemap#index", as: "sitemap", defaults: { format: "xml" }
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  extend FriendlyId
  friendly_id :issue_number

  has_many :articles
  
  validates_presence_of :title

  mount_uploader :poster_image, ImageUploader
  mount_uploader :cover_image, CoverUploader
  mount_uploader :cover_spread, ImageUploader

  COLOR_SCHEMES = [ :dark, :light ]
  enum color_scheme: COLOR_SCHEMES

  scope :all_published, -> { where('release_date <= ?', Date.today) }

  def published?
    release_date <= Date.today
  end

  def self.latest_issue
    Issue.all_published.order('issue_number desc').first
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :require_login, except: [:show, :index]
  before_action :set_issue, only: [:show, :edit, :update, :destroy, :preview]

  def index
    @issues = Issue.all.order(issue_number: :desc)
    if signed_in?
      @featured_issue = @issues.first
    else
      @featured_issue = Issue.latest_issue
    end
  end

  def show
    @articles = @issue.articles.order(priority_order: :asc)
    if !@issue.published? && !signed_in?
      redirect_to issues_path
    end
  end

  def new
    @issue = Issue.new
  end

  def edit
  end

  def create
    @issue = Issue.new(issue_params)
    if @issue.save
      redirect_to @issue, notice: 'Issue was successfully created.'
    else
      render :new
    end
  end

  def update
    if @issue.update(issue_params)
      redirect_to @issue, notice: 'Issue was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to admin_path, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preview
    render layout: 'frontpage'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_issue
    @issue = Issue.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def issue_params
    params.require(:issue).permit(:title, :release_date, :issue_number, :poster_image, :cover_image, :cover_spread, :color_scheme)
  end
end

app/views/issues/_article.html.slim
- if article.published? || signed_in?
  = link_to article_path(article)
    .bg-list-item.stretchy-wrapper style=("background-image: url(#{article.poster_image.to_s});")
      .stretchy-wrapper-child
        - unless article.published?
          .unpublished-marker.has-tip aria-haspopup="true" data-tooltip="" data-options="show_on:medium; show_on:large; disable_for_touch:true" title="Not published" 
            = fa_icon "eye-slash"
        / .stretchy-container
        .item-title
          h2 class="#{article.color_scheme}" 
            em.skinny = article.category.name 
            span.skinny = " | " 
            = article.title

app/views/issues/_form.html.slim
= simple_form_for(@issue, html: {multipart: true}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :issue_number, as: :integer
    = f.input :release_date
    = f.input :color_scheme, collection: Issue::COLOR_SCHEMES, as: :radio_buttons
    br
    = f.input :cover_image, as: :file, label: "Cover Image (Width: 300px, Height: 450px)"
    = image_tag @issue.cover_image.to_s, class: 'x-small-buffer' if @issue.cover_image
    br
    br
    = f.input :cover_spread, as: :file, label: "Cover Spread (Width: 1000px, Height: 750px)"
    = image_tag @issue.cover_spread.to_s, class: 'x-small-buffer' if @issue.cover_spread
    br
    br
    = f.input :poster_image, as: :file, label: "Poster image (Displays as homepage background)"
    = image_tag @issue.poster_image.to_s, class: 'x-small-buffer' if @issue.poster_image
    em = link_to '(Preview as homepage)', preview_issue_path(@issue), target: "_blank" if @issue.id
    br
    br

  .form-actions
    = f.button :submit, class: 'success'

app/views/issues/_issue.html.slim
- if issue.published? || signed_in?
  span
  .columns.medium-3.small-6.text-center
    = link_to '#cover'
      = image_tag("#{issue.cover_image.thumb.to_s}", class: "cover-thumbnail", data: {image_src: "#{issue.cover_spread.to_s}", issue_number: issue.issue_number},  alt: "#{issue.title} Cover Thumbnail")
    = link_to issue_path(issue)
      .issue-title-link = "#{issue.title.upcase} - ISSUE #{issue.issue_number}"

app/views/issues/edit.html.slim
h3 Editing issue
== render 'form'
p
  = link_to 'Show ', @issue
  ' |
  = link_to 'Back to admin', admin_path

app/views/issues/index.html.slim
- meta title: "All Issues", 
  description: "Showcasing all Conteu Magazine issues. Read current issue: #{@featured_issue.title} - Issue #{@featured_issue.issue_number}",
  keywords: %w(Conteu Magazine Slow Living Lifestyle Issues)
.featured-issue.row.page-gradient
  .columns.medium-12.small-12
    = link_to issue_path(@featured_issue), class: "featured-cover-link"
      = image_tag(@featured_issue.cover_spread.to_s, id: "cover", class: "cover-spread", alt: "Featured Cover Spread")
    .small-buffer
    .text-center
      = link_to issue_path(@featured_issue), class: 'featured-issue-button-link'
        .featured-issue-button class="dark"
          em.btn-text = "Read Issue #{@featured_issue.issue_number}"
    br
    hr
.small-buffer
.row
  == render partial: 'issues/issue', collection: @issues

app/views/issues/new.html.slim
h3 New issue
== render 'form'
= link_to 'Back to admin', admin_path

app/views/issues/preview.html.slim
.homepage-buffer.text-center
    .medium-buffer
      = image_tag("logo_#{@issue.color_scheme}.png", alt: "Conteu Logo", class: "front-page-conteu-logo")
    .small-buffer
    = link_to issue_path(@issue)
      .featured-issue-button class="#{@issue.color_scheme}"
        span.btn-title = @issue.title.upcase
        em.btn-text   issue 
        em.btn-number = @issue.issue_number

app/views/issues/show.html.slim
- meta title: "Issue #{@issue.issue_number} - #{@issue.title}", 
  description: "Issue #{@issue.issue_number} - #{@issue.title}. Kindled from the French word conteur, meaning storyteller, Conteu Magazine is a collection of stories that support a more meaningful lifestyle. Released quarterly, each issue follows a different theme with stories falling into three distinct categories namely, Maker, Thinker and Adventurer.",
  keywords: %w(Conteu Magazine Slow Living Lifestyle)
.columns.medium-12
  == render partial: 'issues/article', collection: @articles

  .x-small-buffer
    - if signed_in? 
      = link_to 'Edit ', edit_issue_path(@issue)
      '|
      = link_to 'Back to admin ', admin_path
      '|