config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#home'

  resources :issues do
    member do
      get 'preview'
    end
  end
  resources :articles, except: [:index]
  resources :categories, except: [:index, :show]
  resources :events

  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'clearance/sessions', only: [:create]

  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password,
      controller: 'clearance/passwords',
      only: [:create, :edit, :update]
  end

  get '/admin' => 'pages#admin', as: 'admin'
  get '/subscribe' => 'pages#subscribe', as: 'subscribe'

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  # get '/sign_up' => 'clearance/users#new', as: 'sign_up'
  get "sitemap.xml" => "sitemap#index", as: "sitemap", defaults: { format: "xml" }
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_photos
  mount_uploader :poster_image, ImageUploader

  validates_presence_of :name

  accepts_nested_attributes_for :event_photos, reject_if: :all_blank, allow_destroy: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login, except: [:show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.where(published: true).order(date: :desc)
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to admin_path, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to admin_path, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to admin_path, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.includes(:event_photos).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :venue, :date, :description, :published, :poster_image, event_photos_attributes: [:id, :order, :photo, :caption, :_destroy])
  end
end

app/views/events/_card.html.slim
li
  .event-card
    = link_to event_path(event)
      = image_tag event.poster_image.to_s
      .text-center
        h3 = event.name

app/views/events/_event_photo_fields.html.slim
.nested-fields.event-photo-fields.x-small-buffer
  .row
    = f.input :order, as: :hidden
    .columns.small-4
      - if f.object.photo.present?
        = image_tag f.object.photo.to_s
      = f.input :photo, label: false
    .columns.small-6
      = f.input :caption, as: :text
    .columns.small-2
      = link_to_remove_association "remove photo", f, class: 'button tiny alert'

app/views/events/_form.html.slim
= simple_form_for(@event, html: { multipart: true }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :venue
    = f.input :date
    = f.input :description
    = f.input :published
    br
    - if @event.poster_image.present?
      = image_tag @event.poster_image.to_s
    = f.input :poster_image, label: 'Poster image (400x100px)'
    br
    h4 Photos
    #event_photos
      = f.simple_fields_for :event_photos do |photo|
        = render 'event_photo_fields', f: photo
    br
    .links
      = link_to_add_association 'add photo', f, :event_photos, class: 'button small'
  br
  br
  .form-actions
    = f.button :submit, 'Save', class: 'success'

app/views/events/edit.html.slim
h3 Editing event
== render 'form'
= link_to 'Back', admin_path

app/views/events/index.html.slim
- meta title: "Events",
  description: "Kindled from the French word conteur, meaning storyteller, Conteu Magazine is a collection of stories that support a more meaningful lifestyle. Released quarterly, each event follows a different theme with stories falling into three distinct categories namely, Maker, Thinker and Adventurer.",
  keywords: %w(Conteu Magazine Slow Living Lifestyle)
.columns.medium-12
  - if @events.present?
    ul.small-block-grid-2
      - @events.each do |event|
        == render partial: "events/card", locals: {event: event}
  - else
    h1 Events coming soon

app/views/events/new.html.slim
h3 New event
== render 'form'
= link_to 'Back', admin_path

app/views/events/show.html.slim
- meta title: "#{@event.name}", 
  description: "#{@event.description}",
  keywords: %w(Conteu Magazine Slow Living Lifestyle)

.columns.medium-12.article
  .text-center
    h2.article-heading = @event.name.upcase
    - if @event.venue.present?
      .sub-heading.author = "#{@event.venue.upcase} - #{@event.date}"
      hr
    - if @event.description.present?
      = @event.description
      hr
  - @event.event_photos.each do |event_photo|
    = image_tag event_photo.photo.to_s
    = event_photo.caption

  / br
  / .columns.small-6.full-width-columns.permanent-column
  /   - if @previous_article
  /     = link_to article_path(@previous_article) do
  /       = fa_icon 'angle-double-left'
  /       span.next-article-link = @previous_article.title
  / .columns.small-6.text-right.full-width-columns
  /   - if @next_article
  /     = link_to article_path(@next_article)
  /       span.next-article-link = @next_article.title
  /       = fa_icon 'angle-double-right'

  - if signed_in?
    .columns.small-12.full-width-columns
      = link_to 'Edit ', edit_event_path(@event)