config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#home'

  resources :issues do
    member do
      get 'preview'
    end
  end
  resources :articles, except: [:index]
  resources :categories, except: [:index, :show]
  resources :events

  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'clearance/sessions', only: [:create]

  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password,
      controller: 'clearance/passwords',
      only: [:create, :edit, :update]
  end

  get '/admin' => 'pages#admin', as: 'admin'
  get '/subscribe' => 'pages#subscribe', as: 'subscribe'

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  # get '/sign_up' => 'clearance/users#new', as: 'sign_up'
  get "sitemap.xml" => "sitemap#index", as: "sitemap", defaults: { format: "xml" }
end

app/views/pages/_mailchimp_form.html.erb
<!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup">
<form action="//conteumagazine.us11.list-manage.com/subscribe/post?u=bc98cf4ca794e5e8d118d466e&amp;id=bd86a804e4" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
  <h3>Join the Conteu Community</h3>
  <h6>Conteu releases a new issue every quarter. We would love for you to enjoy the next one. Sign up for free below and we'll let you know once it's released.</h6>
  <br/> 
<div class="mc-field-group">
  <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
  <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
  <label for="mce-FNAME">First Name </label>
  <input type="text" value="" name="FNAME" class="" id="mce-FNAME">
</div>
<div class="mc-field-group">
  <label for="mce-LNAME">Last Name </label>
  <input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
<br/>
  <div id="mce-responses" class="clear">
    <div class="response" id="mce-error-response" style="display:none"></div>
    <div class="response" id="mce-success-response" style="display:none"></div>
  </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_bc98cf4ca794e5e8d118d466e_bd86a804e4" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe to our newsletter" name="subscribe" id="mc-embedded-subscribe" class=""></div>
    </div>
</form>
</div>
<br>

<!--End mc_embed_signup-->

app/views/pages/admin.html.slim
.full-width-row
  .columns.medium-8.medium-centered.small-10.small-centered
    h3 Admin
    table
      tbody
        - @issues.each do |issue|
          tr
            th Issue #{issue.issue_number}.
            th = link_to issue.title, issue_path(issue)
            th = link_to edit_issue_path(issue) do
                = fa_icon "pencil-square-o"
            th 
              - if issue.published?
                = fa_icon "eye" 
              - else
                = fa_icon "eye-slash"
            th = link_to issue, data: {:confirm => 'Delete ISSUE - Are you sure?'}, :method => :delete do
                = fa_icon "trash-o"
          - issue.articles.order(priority_order: :asc).each do |article|
            tr
              td = article.priority_order
              td = link_to article.title, article_path(article)
              td = link_to edit_article_path(article) do
                = fa_icon "pencil-square-o"
              td 
                - if article.published?
                  = fa_icon "eye" 
                - else
                  = fa_icon "eye-slash"
              td = link_to article, data: {:confirm => 'Delete ARTICLE - Are you sure?'}, :method => :delete do
                = fa_icon "trash-o"

    .admin-options
      = link_to 'New Article ', new_article_path
      ' | 
      = link_to 'New Issue', new_issue_path
    
    br
    
    table
      tbody
        tr
          th colspan="4" Categories
        - @categories.each do |category|
          tr
            td width="200" = category.name
            td = link_to edit_category_path(category) do
              = fa_icon "pencil-square-o"
            td = link_to category, data: {:confirm => 'Are you sure?'}, :method => :delete do
              = fa_icon "trash-o"
            td
    .admin-options
      = link_to 'New Category ', new_category_path
    br

    table
      tbody
        tr
          th colspan="4" Events
        - @events.each do |event|
          tr
            td width="200" = event.name
            td = link_to edit_event_path(event) do
              = fa_icon "pencil-square-o"
            td 
              - if event.published?
                = fa_icon "eye" 
              - else
                = fa_icon "eye-slash"
            td = link_to event, data: {:confirm => 'Are you sure?'}, :method => :delete do
              = fa_icon "trash-o"
    .admin-options
      = link_to 'New Event ', new_event_path

app/views/pages/home.html.slim
- meta description: "Kindled from the French word conteur, meaning storyteller, Conteu Magazine is a collection of stories that support a more meaningful lifestyle. Released quarterly, each issue follows a different theme with stories falling into three distinct categories namely, Maker, Thinker and Adventurer.",
  keywords: %w(Conteu Magazine Slow Living Lifestyle)
.homepage-buffer.text-center
    .small-buffer
    = image_tag("logo_#{@issue.color_scheme}.png", alt: "Conteu Logo", class: "front-page-conteu-logo")
    .small-buffer
    .small-buffer.show-for-medium-up

    = link_to issue_path(@issue)
      .featured-issue-button class="#{@issue.color_scheme}"
        span.btn-title = @issue.title.upcase
        em.btn-text issue 
        em.btn-number = @issue.issue_number
    / = link_to issues_path
    /   .featured-issue-button class="#{@issue.color_scheme}"
    /     span.btn-title = 'All Issues'

app/views/pages/subscribe.html.slim
- meta title: "Subscribe", 
  description: "Subscribe to our newsletter and get notified when new issues are released.",
  keywords: %w(Conteu Magazine Slow Living Lifestyle)
.full-width-row
  .columns.medium-8.medium-centered.small-10.small-centered
    .columns.medium-12
      == render 'pages/mailchimp_form'