config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#home'

  resources :issues do
    member do
      get 'preview'
    end
  end
  resources :articles, except: [:index]
  resources :categories, except: [:index, :show]
  resources :events

  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'clearance/sessions', only: [:create]

  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password,
      controller: 'clearance/passwords',
      only: [:create, :edit, :update]
  end

  get '/admin' => 'pages#admin', as: 'admin'
  get '/subscribe' => 'pages#subscribe', as: 'subscribe'

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  # get '/sign_up' => 'clearance/users#new', as: 'sign_up'
  get "sitemap.xml" => "sitemap#index", as: "sitemap", defaults: { format: "xml" }
end

app/views/layouts/_admin_navigation.html.slim
.admin-nav.full-width-row 
  .columns.medium-10.medium-centered.small-10.small-centered
    .right
      = link_to admin_path do
        = fa_icon "cog"
      = link_to sign_out_path, method: :delete do
        = fa_icon "sign-out"
.x-small-buffer

app/views/layouts/_footer.html.slim
footer.full-width-row
  .columns.medium-8.medium-centered.small-10.small-centered
    / .x-small-buffer
    hr
    .row
      .columns.small-6.full-width-columns
        .footer-link.no-left = link_to 'ALL ISSUES', issues_path 
        .divider |
        .footer-link = link_to 'OUR STORY', article_path(7)
        .divider |
        .footer-link = link_to 'EVENTS', events_path
        .divider |
        .footer-link = link_to 'SUBSCRIBE', subscribe_path


      .columns.small-6.text-right.full-width-columns
        span.instagram-icon = link_to "https://instagram.com/conteu_magazine", target: '_blank' do
          = fa_icon 'instagram'

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production"  %>
  <script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41032983-5', 'auto');
    ga('send', 'pageview');
  </script>
<% end %>

app/views/layouts/_header.html.slim
header.full-width-row.header-bg
  .columns.medium-6.end.small-12.medium-push-4
    .small-buffer
    .logo-container
      = link_to root_path do
        = image_tag("logo_dark_small.png", alt: "Conteu Logo", class: "conteu-logo")
  .columns.medium-2.medium-offset-2.small-12.medium-pull-8
    - if @issue && @issue.id
      .small-buffer.visible-for-medium-up
      = link_to issue_path(@issue)
        h1.issue-title.no-spacing ISSUE #{@issue.issue_number}: #{@issue.title.upcase}
      .x-small-buffer.visible-for-small-only

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    = metamagic site: "Conteu Magazine", title: [:title, :site], separator: " | "
    == stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true
    / Modernizr is required for Zurb Foundation
    == javascript_include_tag 'vendor/modernizr'
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    - if signed_in?
      == render 'layouts/admin_navigation'
    main[role="main"]
      == render 'layouts/header'
      .full-width-row
        .columns.medium-8.medium-centered.small-10.small-centered.full-width-columns
          .small-buffer
          == yield
      == render 'layouts/footer'
    == render 'layouts/google_analytics'

app/views/layouts/frontpage.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    = metamagic site: "Conteu Magazine", title: [:title, :site], separator: " | "
    meta property="og:image" content="https://s3.amazonaws.com/conteu/uploads/global/conteu-og-logo.png"
    == stylesheet_link_tag "application", media: 'all'
    / Modernizr is required for Zurb Foundation
    == javascript_include_tag 'vendor/modernizr'
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body.frontpage style=("background-image: url(#{@issue.poster_image.to_s});")
    - if signed_in?
      == render 'layouts/admin_navigation'
    main[role="main"]
      == yield
    == render 'layouts/google_analytics'